### ISSUE TITLE
Attach to [data-*] attribute

### ISSUE THREAD

**Issue by dnasir** [IndigoUnited/jquery.simplemarquee#1]
I think it would be useful to be able to attach the plugin to an element simply by including a data-\* attribute i.e. `<div data-simplemarquee></div>` similar to how Bootstrap plugins work. Similarly, plugin options can also be passed using the data-\* attribute.

**Comment by satazor** [comment]
The goal of this plugin is simplicity, I really don't wan't to add cruft for "auto" initialisation. If you want this, you can do this "outside".. Just create a function that runs on `domready` that finds those elements and init them with `.data()` as the options.
