### ISSUE TITLE
jQuery 1.7.2 issue

### ISSUE THREAD

**Issue by sonnety** [IndigoUnited/jquery.simplemarquee#2]
Not working with jQuery 1.7.2 on opera.

**Comment by satazor** [comment]
jquery 1.7 is quite old. Does the issue happens in earlier  versions of jquery?

**Comment by sonnety** [comment]
I don't know but i am using  jQuery 1.7.2 and it working on firefox and chrome but not on opera.

**Comment by satazor** [comment]
Well feel free to identify the issue and do a PR, closing it for now.
