### ISSUE TITLE
Thanks for the plugin, any info about browsers support?

### ISSUE THREAD

**Issue by boynet** [IndigoUnited/jquery.simplemarquee#3]
I can see that you wrote about jQuery.Marquee that

> It has unnecessary cruft to support older browsers

**Comment by satazor** [comment]
It supports IE>=10. Can you do a PR saying that in the README?

**Comment by satazor** [comment]
Actually I mention the browser support in the How to use section but feel free to make it more obvious

**Comment by boynet** [comment]
missed that one, thanks, maybe you could add header "browser support"
