### ISSUE TITLE
Good plugin, support for containers without a width specified? 

### ISSUE THREAD

**Issue by mscreenie** [IndigoUnited/jquery.simplemarquee#7]
Looks good, but does this support containers without a fixed width?

I've seen other plugins that get the divs computed width when a width is not present

**Comment by satazor** [comment]
Yes it should work. Are you having any problems?

**Comment by mscreenie** [comment]
TheI haven't tested actually but only a few plugins actually support this, most just fail because they expect a fixed width and don't handle for a fluid like width auto or 100 percent.
