### ISSUE TITLE
Updating the marquee

### ISSUE THREAD

**Issue by stygiansabyss** [IndigoUnited/jquery.simplemarquee#8]
Quick question.  Is there a way to update the speed of the marquee after its been loaded and without destroying it?

```
$('.text-marquee').simplemarquee('destroy')
                          .simplemarquee({
                            speed:              this.settings.scroll_speed,
                            delayBetweenCycles: 0,
                            cycles:             'infinity',
                          }).simplemarquee('update')
```

This works, but destroying it causes it to restart.  Removing the destroy doesn't change the speed at all.

Thanks

**Comment by satazor** [comment]
There's no way at the moment, I didn't wanted to overcomplicate the plugin. We could had a method to update the options, but there are options that can't be changed at the moment (handleResize, etc).

**Comment by stygiansabyss** [comment]
Ahh.  Could it be possible to have a limited set of options be update capable?  It's only the speed I need to update on the fly.

**Comment by satazor** [comment]
Depends on the complexity added. If the footprint to add the functionality is small, I will merge it gladly.

**Comment by stygiansabyss** [comment]
The solution we came up with was the following.

```
let jqEl = $('.text-marquee')

var instance            = jqEl.data('_simplemarquee')
instance._options.speed = this.settings.scroll_speed
instance.update(false)
```

Does this seem proper and correct to you?

**Comment by satazor** [comment]
Yes that certainly works, still it's not "recommended" to access "private" properties, such as `_options`.

**Comment by satazor** [comment]
Closing this for now.
